# Generated by Django 5.2.12 on 2026-04-02 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SaleRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "Sale Record",
                "verbose_name_plural": "Sale Records",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StockEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "Stock Entry",
                "verbose_name_plural": "Stock Entries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "kg"), ("piece", "piece")],
                        default="kg",
                        max_length=10,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sell Price"
                    ),
                ),
                (
                    "svg_icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="grocery/icons/",
                        verbose_name="Icon",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Low Stock Threshold",
                    ),
                ),
                (
                    "expiry_note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Expiry Note",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="grocery.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["category__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Quantity"
                    ),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Sell Price per Unit at Time of Sale",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="grocery.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="grocery.salerecord",
                        verbose_name="Sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Item",
                "verbose_name_plural": "Sale Items",
            },
        ),
        migrations.CreateModel(
            name="StockEntryItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Quantity"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Purchase Price per Unit",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="grocery.stockentry",
                        verbose_name="Entry",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_items",
                        to="grocery.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Entry Item",
                "verbose_name_plural": "Stock Entry Items",
            },
        ),
    ]
