# Generated by Django 5.2.12 on 2026-04-02 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grocery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="svg_icon",
            field=models.FileField(
                blank=True, null=True, upload_to="grocery/icons/", verbose_name="Icon"
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="sell_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Sell Price per Unit at Time of Sale",
            ),
        ),
        migrations.AlterField(
            model_name="stockentryitem",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Purchase Price per Unit",
            ),
        ),
        migrations.AlterField(
            model_name="stockentryitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
    ]
