# Generated by Django 5.2.12 on 2026-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grocery", "0005_storeprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeprofile",
            name="search_radius_km",
            field=models.IntegerField(default=5),
        ),
    ]
