# Generated by Django 5.2.12 on 2026-04-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grocery", "0006_alter_storeprofile_search_radius_km"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storeprofile",
            options={
                "verbose_name": "Mağaza Profili",
                "verbose_name_plural": "Mağaza Profilleri",
            },
        ),
    ]
