# Generated by Django 5.2.12 on 2026-04-17 07:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grocery", "0009_salerecord_payment_method_returnrecord_returnitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="stockentryitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="Quantity",
            ),
        ),
    ]
